# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.infrastructure_network import InfrastructureNetwork

class TestInfrastructureNetwork(unittest.TestCase):
    """InfrastructureNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfrastructureNetwork(self):
        """Test InfrastructureNetwork"""
        # inst = InfrastructureNetwork()

if __name__ == '__main__':
    unittest.main()
