# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.remediate_node_response import RemediateNodeResponse

class TestRemediateNodeResponse(unittest.TestCase):
    """RemediateNodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemediateNodeResponse:
        """Test RemediateNodeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemediateNodeResponse`
        """
        model = RemediateNodeResponse()
        if include_optional:
            return RemediateNodeResponse(
                node_id = 'g0386',
                remediate_status = 'accepted',
                rejection_cause = ''
            )
        else:
            return RemediateNodeResponse(
                node_id = 'g0386',
                remediate_status = 'accepted',
        )
        """

    def testRemediateNodeResponse(self):
        """Test RemediateNodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
