# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.mks2_worker_node_registration_status import Mks2WorkerNodeRegistrationStatus

class TestMks2WorkerNodeRegistrationStatus(unittest.TestCase):
    """Mks2WorkerNodeRegistrationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMks2WorkerNodeRegistrationStatus(self):
        """Test Mks2WorkerNodeRegistrationStatus"""
        # inst = Mks2WorkerNodeRegistrationStatus()

if __name__ == '__main__':
    unittest.main()
