# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.fleet_health_response import FleetHealthResponse

class TestFleetHealthResponse(unittest.TestCase):
    """FleetHealthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetHealthResponse:
        """Test FleetHealthResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetHealthResponse`
        """
        model = FleetHealthResponse()
        if include_optional:
            return FleetHealthResponse(
                fleet_id = 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6',
                status = 'healthy',
                kubernetes_health = { },
                node_health = [
                    vpcloud_client.models.node_health.NodeHealth(
                        node_id = 'node-12345', 
                        status = 'healthy', 
                        last_updated_at = 1755817319000, )
                    ]
            )
        else:
            return FleetHealthResponse(
                fleet_id = 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6',
        )
        """

    def testFleetHealthResponse(self):
        """Test FleetHealthResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
