# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.mks2_pod import Mks2Pod

class TestMks2Pod(unittest.TestCase):
    """Mks2Pod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Mks2Pod:
        """Test Mks2Pod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Mks2Pod`
        """
        model = Mks2Pod()
        if include_optional:
            return Mks2Pod(
                name = '',
                namespace = '',
                node_name = '',
                phase = 'Pending',
                status = '',
                ip = '',
                host_ip = '',
                restarts = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                labels = {
                    'key' : ''
                    },
                conditions = [
                    vpcloud_client.models.mks2_pod_condition.Mks2PodCondition(
                        type = 'Ready', 
                        status = null, 
                        reason = '', 
                        message = '', 
                        last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                containers = [
                    vpcloud_client.models.mks2_pod_container_status.Mks2PodContainerStatus(
                        name = '', 
                        ready = True, 
                        restart_count = 56, 
                        state = null, 
                        reason = '', 
                        message = '', 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return Mks2Pod(
                name = '',
                namespace = '',
        )
        """

    def testMks2Pod(self):
        """Test Mks2Pod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
