# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VMs provisioning and managing service.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.fleet_node import FleetNode

class TestFleetNode(unittest.TestCase):
    """FleetNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetNode:
        """Test FleetNode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetNode`
        """
        model = FleetNode()
        if include_optional:
            return FleetNode(
                node_name = 'g0388',
                state = 'ACTIVE',
                public_ip = '10.9.41.182'
            )
        else:
            return FleetNode(
                node_name = 'g0388',
                state = 'ACTIVE',
                public_ip = '10.9.41.182',
        )
        """

    def testFleetNode(self):
        """Test FleetNode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
