# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VMs provisioning and managing service.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest
from unittest.mock import Mock, patch, MagicMock
from vpcloud_client.api.monitoring_api import MonitoringApi
from vpcloud_client.exceptions import ApiException
from vpcloud_client import ApiClient
from test.utils import create_test_config, MockResponse


class TestMonitoringApi:
    """MonitoringApi unit tests"""

    @pytest.fixture
    def api_instance(self):
        """Create API instance for testing."""
        config = create_test_config()
        return MonitoringApi(api_client=ApiClient(config))

    def test_get_fleet_grafana_dashboards_success(self, api_instance):
        """Test successful get_fleet_grafana_dashboards request.
        
        Get Grafana dashboards for a specific fleet
        """
        # Mock successful response
        mock_response = MockResponse(200, data=b'{"result": "success"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test implementation
            pass

    def test_get_fleet_grafana_dashboards_error(self, api_instance):
        """Test get_fleet_grafana_dashboards error handling.
        
        Get Grafana dashboards for a specific fleet
        """
        # Mock error response
        mock_response = MockResponse(400, data=b'{"error": "bad request"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test error handling
            pass

    def test_list_fleet_grafana_dashboards_success(self, api_instance):
        """Test successful list_fleet_grafana_dashboards request.
        
        List Grafana dashboards for all fleets
        """
        # Mock successful response
        mock_response = MockResponse(200, data=b'{"result": "success"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test implementation
            pass

    def test_list_fleet_grafana_dashboards_error(self, api_instance):
        """Test list_fleet_grafana_dashboards error handling.
        
        List Grafana dashboards for all fleets
        """
        # Mock error response
        mock_response = MockResponse(400, data=b'{"error": "bad request"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test error handling
            pass

