# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.remediate_node_request import RemediateNodeRequest

class TestRemediateNodeRequest(unittest.TestCase):
    """RemediateNodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemediateNodeRequest:
        """Test RemediateNodeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemediateNodeRequest`
        """
        model = RemediateNodeRequest()
        if include_optional:
            return RemediateNodeRequest(
                node_id = 'g0386',
                message = 'node termal throttle alarm',
                cause = 'TERMAL_THROTTLE'
            )
        else:
            return RemediateNodeRequest(
                node_id = 'g0386',
                message = 'node termal throttle alarm',
                cause = 'TERMAL_THROTTLE',
        )
        """

    def testRemediateNodeRequest(self):
        """Test RemediateNodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
