# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.mks2_drain_node_request import Mks2DrainNodeRequest

class TestMks2DrainNodeRequest(unittest.TestCase):
    """Mks2DrainNodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Mks2DrainNodeRequest:
        """Test Mks2DrainNodeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Mks2DrainNodeRequest`
        """
        model = Mks2DrainNodeRequest()
        if include_optional:
            return Mks2DrainNodeRequest(
                grace_period_seconds = 30,
                delete_local_data = True,
                ignore_daemon_sets = True
            )
        else:
            return Mks2DrainNodeRequest(
        )
        """

    def testMks2DrainNodeRequest(self):
        """Test Mks2DrainNodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
