# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.fleet_apps_mks_cluster import FleetAppsMksCluster

class TestFleetAppsMksCluster(unittest.TestCase):
    """FleetAppsMksCluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetAppsMksCluster:
        """Test FleetAppsMksCluster
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetAppsMksCluster`
        """
        model = FleetAppsMksCluster()
        if include_optional:
            return FleetAppsMksCluster(
                cluster_id = 'cluster-123-abc',
                cluster_name = 'my-fleet-mk8s-cluster',
                kubernetes_version = '1.32',
                installation_status = 'ACTIVE',
                cluster_status = 'READY',
                kubeconfig = 'apiVersion: v1\nkind: Config\n...',
                auth_config_b64 = 'eyJraW5kIjoiQXV0aGVudGljYXRpb25Db25maWd1cmF0aW9uIi4uLn0=',
                service_links = vpcloud_client.models.kubernetes_service_links.KubernetesServiceLinks(
                    grafana = 'https://grafana.mks.voltagepark.com/d/abc123/cluster-overview', ),
                control_plane_node_count = 3,
                ready_control_plane_node_count = 3,
                worker_node_count = 8,
                ready_worker_node_count = 8,
                addons = ["prometheus"],
                created_at = '2025-01-15T10:30:00Z'
            )
        else:
            return FleetAppsMksCluster(
                cluster_id = 'cluster-123-abc',
                cluster_name = 'my-fleet-mk8s-cluster',
                installation_status = 'ACTIVE',
        )
        """

    def testFleetAppsMksCluster(self):
        """Test FleetAppsMksCluster"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
