# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.mks2_pod_container_state import Mks2PodContainerState

class TestMks2PodContainerState(unittest.TestCase):
    """Mks2PodContainerState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMks2PodContainerState(self):
        """Test Mks2PodContainerState"""
        # inst = Mks2PodContainerState()

if __name__ == '__main__':
    unittest.main()
