# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.add_storage_view_request import AddStorageViewRequest

class TestAddStorageViewRequest(unittest.TestCase):
    """AddStorageViewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddStorageViewRequest:
        """Test AddStorageViewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddStorageViewRequest`
        """
        model = AddStorageViewRequest()
        if include_optional:
            return AddStorageViewRequest(
                mount_point = '/data',
                size = 536870912000,
                soft_limit = 56,
                hard_limit = 56,
                protection_policy = vpcloud_client.models.storage_protection_policy.StorageProtectionPolicy(
                    start_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    every = '', 
                    keep_local = '', 
                    keep_remote = '', ),
                provision = True
            )
        else:
            return AddStorageViewRequest(
                mount_point = '/data',
        )
        """

    def testAddStorageViewRequest(self):
        """Test AddStorageViewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
