# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pytest
from unittest.mock import Mock, patch, MagicMock
from vpcloud_client.api.audit_api import AuditApi
from vpcloud_client.exceptions import ApiException
from vpcloud_client import ApiClient
from test.utils import create_test_config, MockResponse


class TestAuditApi:
    """AuditApi unit tests"""

    @pytest.fixture
    def api_instance(self):
        """Create API instance for testing."""
        config = create_test_config()
        return AuditApi(api_client=ApiClient(config))

    def test_get_audit_log_export_success(self, api_instance):
        """Test successful get_audit_log_export request.
        
        Check the 90-day audit log export and get its download URL
        """
        # Mock successful response
        mock_response = MockResponse(200, data=b'{"result": "success"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test implementation
            pass

    def test_get_audit_log_export_error(self, api_instance):
        """Test get_audit_log_export error handling.
        
        Check the 90-day audit log export and get its download URL
        """
        # Mock error response
        mock_response = MockResponse(400, data=b'{"error": "bad request"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test error handling
            pass

    def test_get_audit_logs_success(self, api_instance):
        """Test successful get_audit_logs request.
        
        List recent audit logs for your organization
        """
        # Mock successful response
        mock_response = MockResponse(200, data=b'{"result": "success"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test implementation
            pass

    def test_get_audit_logs_error(self, api_instance):
        """Test get_audit_logs error handling.
        
        List recent audit logs for your organization
        """
        # Mock error response
        mock_response = MockResponse(400, data=b'{"error": "bad request"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test error handling
            pass

    def test_start_audit_log_export_success(self, api_instance):
        """Test successful start_audit_log_export request.
        
        Start building the 90-day audit log export for your organization
        """
        # Mock successful response
        mock_response = MockResponse(200, data=b'{"result": "success"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test implementation
            pass

    def test_start_audit_log_export_error(self, api_instance):
        """Test start_audit_log_export error handling.
        
        Start building the 90-day audit log export for your organization
        """
        # Mock error response
        mock_response = MockResponse(400, data=b'{"error": "bad request"}')
        with patch.object(api_instance.api_client.rest_client, 'request', 
                         return_value=mock_response):
            # Test error handling
            pass

