# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.node_power_state import NodePowerState

class TestNodePowerState(unittest.TestCase):
    """NodePowerState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodePowerState:
        """Test NodePowerState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodePowerState`
        """
        model = NodePowerState()
        if include_optional:
            return NodePowerState(
                node_id = 'g311',
                power_state = 'On',
                last_operation = vpcloud_client.models.node_power_last_operation.NodePowerLastOperation(
                    operation_id = '', 
                    reset_type = 'ForceRestart', 
                    status = 'ACCEPTED', 
                    queued_at = 56, 
                    completed_at = 56, 
                    verified_power_state = '', 
                    error = vpcloud_client.models.node_power_operation_error.NodePowerOperationError(
                        code = '', 
                        message = '', 
                        reset_issued = 'yes', ), )
            )
        else:
            return NodePowerState(
                node_id = 'g311',
                power_state = 'On',
        )
        """

    def testNodePowerState(self):
        """Test NodePowerState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
