# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.mks2_drain_node_response import Mks2DrainNodeResponse

class TestMks2DrainNodeResponse(unittest.TestCase):
    """Mks2DrainNodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Mks2DrainNodeResponse:
        """Test Mks2DrainNodeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Mks2DrainNodeResponse`
        """
        model = Mks2DrainNodeResponse()
        if include_optional:
            return Mks2DrainNodeResponse(
                node_id = 'g0546',
                evicted = 56,
                failed = [
                    ''
                    ]
            )
        else:
            return Mks2DrainNodeResponse(
                node_id = 'g0546',
        )
        """

    def testMks2DrainNodeResponse(self):
        """Test Mks2DrainNodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
