# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.fleet_apps_mks2_cluster import FleetAppsMks2Cluster

class TestFleetAppsMks2Cluster(unittest.TestCase):
    """FleetAppsMks2Cluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetAppsMks2Cluster:
        """Test FleetAppsMks2Cluster
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetAppsMks2Cluster`
        """
        model = FleetAppsMks2Cluster()
        if include_optional:
            return FleetAppsMks2Cluster(
                cluster_id = '11111111-2222-3333-4444-555555555555',
                cluster_name = 'my-fleet-mks2-cluster',
                kubernetes_version = 'v1.35.0',
                cluster_status = 'ready',
                control_plane_replicas = 2,
                control_plane_size = 'medium',
                datastore_type = 'dedicated',
                nvidia_driver_version = '580.126.20',
                created_at = '2026-01-15T10:30Z',
                node_counts = vpcloud_client.models.fleet_apps_mks2_node_counts.FleetAppsMks2NodeCounts(
                    total = 4, 
                    ready = 3, 
                    not_ready = 1, 
                    pending = 0, )
            )
        else:
            return FleetAppsMks2Cluster(
                cluster_id = '11111111-2222-3333-4444-555555555555',
                cluster_name = 'my-fleet-mks2-cluster',
                kubernetes_version = 'v1.35.0',
                cluster_status = 'ready',
                control_plane_replicas = 2,
                nvidia_driver_version = '580.126.20',
                created_at = '2026-01-15T10:30Z',
                node_counts = vpcloud_client.models.fleet_apps_mks2_node_counts.FleetAppsMks2NodeCounts(
                    total = 4, 
                    ready = 3, 
                    not_ready = 1, 
                    pending = 0, ),
        )
        """

    def testFleetAppsMks2Cluster(self):
        """Test FleetAppsMks2Cluster"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
