# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.audit_log_list_response import AuditLogListResponse

class TestAuditLogListResponse(unittest.TestCase):
    """AuditLogListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditLogListResponse:
        """Test AuditLogListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditLogListResponse`
        """
        model = AuditLogListResponse()
        if include_optional:
            return AuditLogListResponse(
                items = [
                    vpcloud_client.models.audit_log_entry.AuditLogEntry(
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        user_id = '', 
                        operation = '', 
                        method = '', 
                        route = '', 
                        status_code = 56, 
                        auth_outcome = '', 
                        client_ip = '', 
                        user_agent = '', 
                        resource = '', )
                    ]
            )
        else:
            return AuditLogListResponse(
                items = [
                    vpcloud_client.models.audit_log_entry.AuditLogEntry(
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        user_id = '', 
                        operation = '', 
                        method = '', 
                        route = '', 
                        status_code = 56, 
                        auth_outcome = '', 
                        client_ip = '', 
                        user_agent = '', 
                        resource = '', )
                    ],
        )
        """

    def testAuditLogListResponse(self):
        """Test AuditLogListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
