# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.mks2_gpu_info import Mks2GpuInfo

class TestMks2GpuInfo(unittest.TestCase):
    """Mks2GpuInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Mks2GpuInfo:
        """Test Mks2GpuInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Mks2GpuInfo`
        """
        model = Mks2GpuInfo()
        if include_optional:
            return Mks2GpuInfo(
                count = 56,
                model = 'NVIDIA-H100-80GB-HBM3',
                driver_version = '',
                cuda_runtime_version = '',
                memory = '',
                validated = True
            )
        else:
            return Mks2GpuInfo(
        )
        """

    def testMks2GpuInfo(self):
        """Test Mks2GpuInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
