# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.update_storage_view_request import UpdateStorageViewRequest

class TestUpdateStorageViewRequest(unittest.TestCase):
    """UpdateStorageViewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateStorageViewRequest:
        """Test UpdateStorageViewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateStorageViewRequest`
        """
        model = UpdateStorageViewRequest()
        if include_optional:
            return UpdateStorageViewRequest(
                size = 56,
                soft_limit = 56,
                hard_limit = 56
            )
        else:
            return UpdateStorageViewRequest(
        )
        """

    def testUpdateStorageViewRequest(self):
        """Test UpdateStorageViewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
