# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.node_details import NodeDetails

class TestNodeDetails(unittest.TestCase):
    """NodeDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeDetails:
        """Test NodeDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeDetails`
        """
        model = NodeDetails()
        if include_optional:
            return NodeDetails(
                node_name = 'g0546',
                state = 'ACTIVE',
                public_ip = '159.26.86.38',
                fleet_id = 'f81d4fae-7dec-11d0-a765-00a0c91e6bf6',
                power_action_readiness = vpcloud_client.models.power_action_readiness.PowerActionReadiness(
                    ready = True, 
                    blocker_message = '', 
                    warning_message = '', ),
                managed_services = vpcloud_client.models.node_managed_services.NodeManagedServices(
                    kubernetes = vpcloud_client.models.mks2_worker_node_detail.Mks2WorkerNodeDetail(
                        id = 'g0546', 
                        name = '', 
                        registration_status = 'joined', 
                        kubernetes_status = 'Ready', 
                        schedulable = True, 
                        drained = True, 
                        gpu_validated = True, 
                        conditions = [
                            vpcloud_client.models.mks2_node_condition.Mks2NodeCondition(
                                type = 'MemoryPressure', 
                                status = 'False', 
                                reason = '', 
                                message = '', 
                                last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        gpu = vpcloud_client.models.mks2_gpu_info.Mks2GpuInfo(
                            count = 56, 
                            model = 'NVIDIA-H100-80GB-HBM3', 
                            driver_version = '', 
                            cuda_runtime_version = '', 
                            memory = '', 
                            validated = True, ), 
                        registered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        joined_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        labels = {
                            'key' : ''
                            }, 
                        annotations = {
                            'key' : ''
                            }, 
                        public_ip = '', 
                        taints = [
                            vpcloud_client.models.mks2_node_taint.Mks2NodeTaint(
                                key = 'voltagepark.io/maintenance', 
                                value = 'true', 
                                effect = 'NoSchedule', )
                            ], ), )
            )
        else:
            return NodeDetails(
                node_name = 'g0546',
                state = 'ACTIVE',
                public_ip = '159.26.86.38',
                power_action_readiness = vpcloud_client.models.power_action_readiness.PowerActionReadiness(
                    ready = True, 
                    blocker_message = '', 
                    warning_message = '', ),
        )
        """

    def testNodeDetails(self):
        """Test NodeDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
