# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vpcloud_client.models.mks2_worker_node_list import Mks2WorkerNodeList

class TestMks2WorkerNodeList(unittest.TestCase):
    """Mks2WorkerNodeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Mks2WorkerNodeList:
        """Test Mks2WorkerNodeList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Mks2WorkerNodeList`
        """
        model = Mks2WorkerNodeList()
        if include_optional:
            return Mks2WorkerNodeList(
                items = [
                    vpcloud_client.models.mks2_worker_node.Mks2WorkerNode(
                        id = 'g0546', 
                        registration_status = 'joined', 
                        kubernetes_status = 'Ready', 
                        schedulable = True, 
                        gpu_validated = True, )
                    ],
                meta = vpcloud_client.models.mks2_worker_node_list_meta.Mks2WorkerNodeListMeta(
                    next_cursor = '', )
            )
        else:
            return Mks2WorkerNodeList(
        )
        """

    def testMks2WorkerNodeList(self):
        """Test Mks2WorkerNodeList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
