# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from vpcloud_client.models.fleet_apps_mks2_cluster import FleetAppsMks2Cluster
from vpcloud_client.models.fleet_apps_mks_cluster import FleetAppsMksCluster
from vpcloud_client.models.slurm_parameters import SlurmParameters
from typing import Optional, Set
from typing_extensions import Self

class FleetApps(BaseModel):
    """
    Fleet applications configuration. mk8s (legacy MKS-1) and mks2 are mutually exclusive: at most one of them may be 'enabled' on the same fleet.
    """ # noqa: E501
    mk8s: Optional[StrictStr] = Field(default=None, description="Enable or disable MK8s (managed Kubernetes, MKS-1) for this fleet. Mutually exclusive with mks2.")
    mks2: Optional[StrictStr] = Field(default=None, description="Enable or disable MKS-2 (Kamaji-based managed Kubernetes) for this fleet. Mutually exclusive with mk8s.")
    slurm: Optional[StrictStr] = Field(default=None, description="Enable or disable Slurm for this fleet")
    mk8s_cluster: Optional[FleetAppsMksCluster] = Field(default=None, description="MK8s (MKS-1) cluster information (only present when mk8s is enabled)", alias="mk8sCluster")
    mks2_cluster: Optional[FleetAppsMks2Cluster] = Field(default=None, description="MKS-2 cluster information (only present when mks2 is enabled)", alias="mks2Cluster")
    slurm_parameters: Optional[SlurmParameters] = Field(default=None, description="Slurm configuration (only present when slurm is enabled)", alias="slurmParameters")
    __properties: ClassVar[List[str]] = ["mk8s", "mks2", "slurm", "mk8sCluster", "mks2Cluster", "slurmParameters"]

    @field_validator('mk8s')
    def mk8s_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('mks2')
    def mks2_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('slurm')
    def slurm_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FleetApps from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mk8s_cluster
        if self.mk8s_cluster:
            _dict['mk8sCluster'] = self.mk8s_cluster.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mks2_cluster
        if self.mks2_cluster:
            _dict['mks2Cluster'] = self.mks2_cluster.to_dict()
        # override the default output from pydantic by calling `to_dict()` of slurm_parameters
        if self.slurm_parameters:
            _dict['slurmParameters'] = self.slurm_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FleetApps from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mk8s": obj.get("mk8s"),
            "mks2": obj.get("mks2"),
            "slurm": obj.get("slurm"),
            "mk8sCluster": FleetAppsMksCluster.from_dict(obj["mk8sCluster"]) if obj.get("mk8sCluster") is not None else None,
            "mks2Cluster": FleetAppsMks2Cluster.from_dict(obj["mks2Cluster"]) if obj.get("mks2Cluster") is not None else None,
            "slurmParameters": SlurmParameters.from_dict(obj["slurmParameters"]) if obj.get("slurmParameters") is not None else None
        })
        return _obj


