# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from vpcloud_client.models.node_health import NodeHealth
from typing import Optional, Set
from typing_extensions import Self

class FleetHealthResponse(BaseModel):
    """
    FleetHealthResponse
    """ # noqa: E501
    fleet_id: StrictStr = Field(description="Unique identifier for the fleet", alias="fleetId")
    status: Optional[StrictStr] = Field(default=None, description="Overall health status of the fleet")
    kubernetes_health: Optional[Dict[str, Any]] = Field(default=None, description="Legacy managed Kubernetes cluster health information")
    node_health: Optional[List[NodeHealth]] = Field(default=None, description="Health information for each node in the fleet")
    __properties: ClassVar[List[str]] = ["fleetId", "status", "kubernetes_health", "node_health"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['healthy', 'unhealthy', 'degraded', 'unknown']):
            raise ValueError("must be one of enum values ('healthy', 'unhealthy', 'degraded', 'unknown')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FleetHealthResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in node_health (list)
        _items = []
        if self.node_health:
            for _item_node_health in self.node_health:
                if _item_node_health:
                    _items.append(_item_node_health.to_dict())
            _dict['node_health'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FleetHealthResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fleetId": obj.get("fleetId"),
            "status": obj.get("status"),
            "kubernetes_health": obj.get("kubernetes_health"),
            "node_health": [NodeHealth.from_dict(_item) for _item in obj["node_health"]] if obj.get("node_health") is not None else None
        })
        return _obj


