# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class GrafanaLogsResponse(BaseModel):
    """
    Dashboard and Explore deep-links for a fleet's VictoriaLogs datasource in Harbor Grafana.
    """ # noqa: E501
    fleet_id: StrictStr = Field(description="Fleet identifier these logs belong to", alias="fleetId")
    available: StrictBool = Field(description="Indicates if logs links can be used. `false` means the fleet is not ACTIVE (links may still be returned for transitional states).")
    datasource_name: StrictStr = Field(description="Grafana datasource display name for this fleet's VictoriaLogs datasource (`{fleetName}-logs`). UID remains the fleet id.", alias="datasourceName")
    dashboard_url: StrictStr = Field(description="Direct link to the Harbor K8s system-logs Dashboard with this fleet's Logs datasource pre-selected. Prefer this over Explore for the default UX.", alias="dashboardUrl")
    explore_url: StrictStr = Field(description="Direct link to Grafana Explore pre-selecting this fleet's Logs datasource. Users authenticate via Auth0 SSO when opening the link.", alias="exploreUrl")
    __properties: ClassVar[List[str]] = ["fleetId", "available", "datasourceName", "dashboardUrl", "exploreUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GrafanaLogsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GrafanaLogsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fleetId": obj.get("fleetId"),
            "available": obj.get("available"),
            "datasourceName": obj.get("datasourceName"),
            "dashboardUrl": obj.get("dashboardUrl"),
            "exploreUrl": obj.get("exploreUrl")
        })
        return _obj


