# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InfrastructureNetwork(str, Enum):
    """
    Network topology type
    """

    """
    allowed enum values
    """
    INFINIBAND = 'infiniband'
    ETHERNET = 'ethernet'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InfrastructureNetwork from a JSON string"""
        return cls(json.loads(json_str))


