# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vpcloud_client.models.mks2_gpu_info import Mks2GpuInfo
from vpcloud_client.models.mks2_node_condition import Mks2NodeCondition
from vpcloud_client.models.mks2_node_taint import Mks2NodeTaint
from vpcloud_client.models.mks2_worker_node_kubernetes_status import Mks2WorkerNodeKubernetesStatus
from vpcloud_client.models.mks2_worker_node_registration_status import Mks2WorkerNodeRegistrationStatus
from typing import Optional, Set
from typing_extensions import Self

class Mks2WorkerNodeDetail(BaseModel):
    """
    Full MKS-2 worker-node detail: a superset of the list summary (Mks2WorkerNode) that adds per-node conditions, GPU info, labels/annotations, registration timestamps, and a live drain observation. Unlike the list (which only includes joined nodes), the per-node detail endpoint also resolves nodes that are registered but not yet joined. `gpuValidated` is a convenience mirror of `gpu.validated`.
    """ # noqa: E501
    id: StrictStr = Field(description="MKS-2 worker-node identifier (registry id). Stable for the lifetime of the registry entry.")
    name: Optional[StrictStr] = Field(default=None, description="Kubernetes node name. Absent until the node has joined the cluster.")
    registration_status: Mks2WorkerNodeRegistrationStatus = Field(alias="registrationStatus")
    kubernetes_status: Optional[Mks2WorkerNodeKubernetesStatus] = Field(default=None, alias="kubernetesStatus")
    schedulable: Optional[StrictBool] = Field(default=None, description="Whether pods can be scheduled on this node (i.e. uncordoned). Absent when the node has not joined yet.")
    drained: Optional[StrictBool] = Field(default=None, description="Live Kubernetes control-plane observation of whether workloads have drained from this node. True when every Pod currently bound to the node is terminal, a mirror Pod, or owned by a live DaemonSet. False when any other Pod remains. Omitted before the node joins or when the tenant cluster cannot be fully observed. This field is independent from `schedulable`; callers preparing maintenance must also verify the node is cordoned. The observation is point-in-time and does not prove that no out-of-band process is running on the host.")
    gpu_validated: Optional[StrictBool] = Field(default=None, description="Whether MKS-2 has run GPU validation against this node and it passed. Convenience mirror of gpu.validated; absent when no GPU info is available.", alias="gpuValidated")
    conditions: Optional[List[Mks2NodeCondition]] = Field(default=None, description="Node conditions passed through from the tenant Kubernetes node, including custom MKS conditions. Absent until the node has joined.")
    gpu: Optional[Mks2GpuInfo] = None
    registered_at: Optional[datetime] = Field(default=None, description="When the node was added to the MKS-2 worker registry.", alias="registeredAt")
    joined_at: Optional[datetime] = Field(default=None, description="When the node joined the Kubernetes cluster. Null/absent for registered-but-not-yet-joined nodes.", alias="joinedAt")
    labels: Optional[Dict[str, StrictStr]] = Field(default=None, description="Kubernetes node labels. Absent until the node has joined.")
    annotations: Optional[Dict[str, StrictStr]] = Field(default=None, description="Kubernetes node annotations. Absent until the node has joined.")
    public_ip: Optional[StrictStr] = Field(default=None, description="Public IPv4 address of the node, used for source-IP-based request routing. Absent when the node was registered without a public IP.", alias="publicIp")
    taints: Optional[List[Mks2NodeTaint]] = Field(default=None, description="Live Kubernetes node taints. Absent until the node has joined. The admin/CX node-details policy uses the maintenance taint for powerActionReadiness.")
    __properties: ClassVar[List[str]] = ["id", "name", "registrationStatus", "kubernetesStatus", "schedulable", "drained", "gpuValidated", "conditions", "gpu", "registeredAt", "joinedAt", "labels", "annotations", "publicIp", "taints"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Mks2WorkerNodeDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "drained",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in conditions (list)
        _items = []
        if self.conditions:
            for _item_conditions in self.conditions:
                if _item_conditions:
                    _items.append(_item_conditions.to_dict())
            _dict['conditions'] = _items
        # override the default output from pydantic by calling `to_dict()` of gpu
        if self.gpu:
            _dict['gpu'] = self.gpu.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in taints (list)
        _items = []
        if self.taints:
            for _item_taints in self.taints:
                if _item_taints:
                    _items.append(_item_taints.to_dict())
            _dict['taints'] = _items
        # set to None if joined_at (nullable) is None
        # and model_fields_set contains the field
        if self.joined_at is None and "joined_at" in self.model_fields_set:
            _dict['joinedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Mks2WorkerNodeDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "registrationStatus": obj.get("registrationStatus"),
            "kubernetesStatus": obj.get("kubernetesStatus"),
            "schedulable": obj.get("schedulable"),
            "drained": obj.get("drained"),
            "gpuValidated": obj.get("gpuValidated"),
            "conditions": [Mks2NodeCondition.from_dict(_item) for _item in obj["conditions"]] if obj.get("conditions") is not None else None,
            "gpu": Mks2GpuInfo.from_dict(obj["gpu"]) if obj.get("gpu") is not None else None,
            "registeredAt": obj.get("registeredAt"),
            "joinedAt": obj.get("joinedAt"),
            "labels": obj.get("labels"),
            "annotations": obj.get("annotations"),
            "publicIp": obj.get("publicIp"),
            "taints": [Mks2NodeTaint.from_dict(_item) for _item in obj["taints"]] if obj.get("taints") is not None else None
        })
        return _obj


