# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vpcloud_client.models.mks2_pod_condition import Mks2PodCondition
from vpcloud_client.models.mks2_pod_container_status import Mks2PodContainerStatus
from vpcloud_client.models.mks2_pod_phase import Mks2PodPhase
from typing import Optional, Set
from typing_extensions import Self

class Mks2Pod(BaseModel):
    """
    A pod in the fleet's MKS-2 cluster. `phase` is the raw Kubernetes pod phase; `status` is a derived human-readable status (e.g. Running, CrashLoopBackOff, Terminating).
    """ # noqa: E501
    name: StrictStr = Field(description="Pod name.")
    namespace: StrictStr = Field(description="Pod namespace.")
    node_name: Optional[StrictStr] = Field(default=None, description="Name of the node the pod is scheduled on. Absent for unscheduled pods.", alias="nodeName")
    phase: Optional[Mks2PodPhase] = Field(default=None, description="Raw Kubernetes pod phase.")
    status: Optional[StrictStr] = Field(default=None, description="Derived human-readable status (e.g. Running, CrashLoopBackOff, Init:0/1, Terminating).")
    ip: Optional[StrictStr] = Field(default=None, description="Pod IP address, when assigned.")
    host_ip: Optional[StrictStr] = Field(default=None, description="IP address of the host node, when assigned.", alias="hostIp")
    restarts: Optional[StrictInt] = Field(default=None, description="Total container restarts across the pod.")
    created_at: Optional[datetime] = Field(default=None, description="Pod creation timestamp.", alias="createdAt")
    started_at: Optional[datetime] = Field(default=None, description="When the pod started running, when reported.", alias="startedAt")
    labels: Optional[Dict[str, StrictStr]] = Field(default=None, description="Pod labels.")
    conditions: Optional[List[Mks2PodCondition]] = Field(default=None, description="Pod conditions reported by Kubernetes (e.g. PodScheduled, Initialized, ContainersReady, Ready).")
    containers: Optional[List[Mks2PodContainerStatus]] = Field(default=None, description="Per-container statuses.")
    __properties: ClassVar[List[str]] = ["name", "namespace", "nodeName", "phase", "status", "ip", "hostIp", "restarts", "createdAt", "startedAt", "labels", "conditions", "containers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Mks2Pod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in conditions (list)
        _items = []
        if self.conditions:
            for _item_conditions in self.conditions:
                if _item_conditions:
                    _items.append(_item_conditions.to_dict())
            _dict['conditions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in containers (list)
        _items = []
        if self.containers:
            for _item_containers in self.containers:
                if _item_containers:
                    _items.append(_item_containers.to_dict())
            _dict['containers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Mks2Pod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "namespace": obj.get("namespace"),
            "nodeName": obj.get("nodeName"),
            "phase": obj.get("phase"),
            "status": obj.get("status"),
            "ip": obj.get("ip"),
            "hostIp": obj.get("hostIp"),
            "restarts": obj.get("restarts"),
            "createdAt": obj.get("createdAt"),
            "startedAt": obj.get("startedAt"),
            "labels": obj.get("labels"),
            "conditions": [Mks2PodCondition.from_dict(_item) for _item in obj["conditions"]] if obj.get("conditions") is not None else None,
            "containers": [Mks2PodContainerStatus.from_dict(_item) for _item in obj["containers"]] if obj.get("containers") is not None else None
        })
        return _obj


