# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vpcloud_client.models.mks2_pod_container_state import Mks2PodContainerState
from typing import Optional, Set
from typing_extensions import Self

class Mks2PodContainerStatus(BaseModel):
    """
    Status of a single container in an MKS-2 pod.
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Container name.")
    ready: Optional[StrictBool] = Field(default=None, description="Whether the container passed its readiness probe.")
    restart_count: Optional[StrictInt] = Field(default=None, description="Number of times the container has restarted.", alias="restartCount")
    state: Optional[Mks2PodContainerState] = Field(default=None, description="Current container state.")
    reason: Optional[StrictStr] = Field(default=None, description="Machine-readable reason for the current state (set when waiting/terminated).")
    message: Optional[StrictStr] = Field(default=None, description="Human-readable message describing the current state.")
    started_at: Optional[datetime] = Field(default=None, description="When the container last started running, when reported.", alias="startedAt")
    __properties: ClassVar[List[str]] = ["name", "ready", "restartCount", "state", "reason", "message", "startedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Mks2PodContainerStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Mks2PodContainerStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "ready": obj.get("ready"),
            "restartCount": obj.get("restartCount"),
            "state": obj.get("state"),
            "reason": obj.get("reason"),
            "message": obj.get("message"),
            "startedAt": obj.get("startedAt")
        })
        return _obj


