# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from vpcloud_client.models.node_managed_services import NodeManagedServices
from vpcloud_client.models.node_state import NodeState
from vpcloud_client.models.power_action_readiness import PowerActionReadiness
from typing import Optional, Set
from typing_extensions import Self

class NodeDetails(BaseModel):
    """
    Consolidated single-node details for the customer node-details page. Composes base physical-node fields (publicIp only — no privateIp / reservationId / nodeResourceName), advisory powerActionReadiness, and optional managedServices. Customer power readiness checks cluster join, cordon, and drain state. Topology, privateIp, reservationId, and nodeResourceName are admin-only (see AdminNodeDetails). Existing list/detail endpoints are unchanged.
    """ # noqa: E501
    node_name: StrictStr = Field(description="Unique identifier for the node (ThunderCat Node.Name / MKS registry id).", alias="nodeName")
    state: NodeState
    public_ip: StrictStr = Field(description="Public IP address of the node", alias="publicIp")
    fleet_id: Optional[StrictStr] = Field(default=None, description="Fleet ID associated with the node, if any", alias="fleetId")
    power_action_readiness: PowerActionReadiness = Field(alias="powerActionReadiness")
    managed_services: Optional[NodeManagedServices] = Field(default=None, alias="managedServices")
    __properties: ClassVar[List[str]] = ["nodeName", "state", "publicIp", "fleetId", "powerActionReadiness", "managedServices"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of power_action_readiness
        if self.power_action_readiness:
            _dict['powerActionReadiness'] = self.power_action_readiness.to_dict()
        # override the default output from pydantic by calling `to_dict()` of managed_services
        if self.managed_services:
            _dict['managedServices'] = self.managed_services.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodeName": obj.get("nodeName"),
            "state": obj.get("state"),
            "publicIp": obj.get("publicIp"),
            "fleetId": obj.get("fleetId"),
            "powerActionReadiness": PowerActionReadiness.from_dict(obj["powerActionReadiness"]) if obj.get("powerActionReadiness") is not None else None,
            "managedServices": NodeManagedServices.from_dict(obj["managedServices"]) if obj.get("managedServices") is not None else None
        })
        return _obj


