# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class NodePowerOperationQueued(BaseModel):
    """
    Confirmation that a power operation was accepted and queued. The operation is asynchronous - use `taskId` to correlate with logs, and re-`GET` the node's power state to observe the outcome.
    """ # noqa: E501
    node_id: StrictStr = Field(description="Node identifier.", alias="nodeId")
    reset_type: StrictStr = Field(description="Power action that was queued. One of `On`, `ForceOff`, `GracefulShutdown`, or `ForceRestart`.", alias="resetType")
    power_state_before: StrictStr = Field(description="Live BMC power state read immediately before queueing the operation.", alias="powerStateBefore")
    status: StrictStr = Field(description="Queue status for the requested operation.")
    task_id: StrictStr = Field(description="Identifier for the queued power operation, for log correlation.", alias="taskId")
    __properties: ClassVar[List[str]] = ["nodeId", "resetType", "powerStateBefore", "status", "taskId"]

    @field_validator('reset_type')
    def reset_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['On', 'ForceOff', 'GracefulShutdown', 'ForceRestart']):
            raise ValueError("must be one of enum values ('On', 'ForceOff', 'GracefulShutdown', 'ForceRestart')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodePowerOperationQueued from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodePowerOperationQueued from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodeId": obj.get("nodeId"),
            "resetType": obj.get("resetType"),
            "powerStateBefore": obj.get("powerStateBefore"),
            "status": obj.get("status"),
            "taskId": obj.get("taskId")
        })
        return _obj


