# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RemediateNodeResponse(BaseModel):
    """
    RemediateNodeResponse
    """ # noqa: E501
    node_id: StrictStr = Field(description="Unique identifier for the node", alias="nodeId")
    remediate_status: StrictStr = Field(description="Status of the remediation request", alias="remediateStatus")
    rejection_cause: Optional[StrictStr] = Field(default=None, description="Reason for rejection if remediation was rejected, null if accepted", alias="rejectionCause")
    __properties: ClassVar[List[str]] = ["nodeId", "remediateStatus", "rejectionCause"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RemediateNodeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rejection_cause (nullable) is None
        # and model_fields_set contains the field
        if self.rejection_cause is None and "rejection_cause" in self.model_fields_set:
            _dict['rejectionCause'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RemediateNodeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodeId": obj.get("nodeId"),
            "remediateStatus": obj.get("remediateStatus"),
            "rejectionCause": obj.get("rejectionCause")
        })
        return _obj


