# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management services.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from vpcloud_client.models.audit_log_export_status_response import AuditLogExportStatusResponse
from vpcloud_client.models.audit_log_list_response import AuditLogListResponse

from vpcloud_client.api_client import ApiClient, RequestSerialized
from vpcloud_client.api_response import ApiResponse
from vpcloud_client.rest import RESTResponseType


class AuditApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_audit_log_export(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AuditLogExportStatusResponse:
        """Check the 90-day audit log export and get its download URL

        Reports the state of your organization's 90-day audit export and, once it is `ready`, returns a short-lived presigned download URL. Start an export with `POST /v1/audit-logs/export` first; this endpoint only reports and never starts one, so it is safe to poll.  **Statuses:** - `notStarted` — no archive exists for today's window and no build is running. Call `POST` to start one. - `running` — a build is in progress. Poll again in a few seconds. - `ready` — the archive is complete; `url` and `expiresAt` are present. - `failed` — the build did not finish; `error` carries a short reason. Call `POST` to try again.  **Format:** gzip-compressed NDJSON (`.ndjson.gz`) — one audit event per line, oldest first.  **Note:** the returned `url` expires within minutes — download promptly, and call this endpoint again for a fresh URL if it lapses. The archive itself persists for the rest of the UTC day. Actions taken by Voltage Park support/admin staff are attributed to their own organization and are not included here.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_audit_log_export_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AuditLogExportStatusResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_audit_log_export_with_http_info(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AuditLogExportStatusResponse]:
        """Check the 90-day audit log export and get its download URL

        Reports the state of your organization's 90-day audit export and, once it is `ready`, returns a short-lived presigned download URL. Start an export with `POST /v1/audit-logs/export` first; this endpoint only reports and never starts one, so it is safe to poll.  **Statuses:** - `notStarted` — no archive exists for today's window and no build is running. Call `POST` to start one. - `running` — a build is in progress. Poll again in a few seconds. - `ready` — the archive is complete; `url` and `expiresAt` are present. - `failed` — the build did not finish; `error` carries a short reason. Call `POST` to try again.  **Format:** gzip-compressed NDJSON (`.ndjson.gz`) — one audit event per line, oldest first.  **Note:** the returned `url` expires within minutes — download promptly, and call this endpoint again for a fresh URL if it lapses. The archive itself persists for the rest of the UTC day. Actions taken by Voltage Park support/admin staff are attributed to their own organization and are not included here.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_audit_log_export_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AuditLogExportStatusResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_audit_log_export_without_preload_content(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Check the 90-day audit log export and get its download URL

        Reports the state of your organization's 90-day audit export and, once it is `ready`, returns a short-lived presigned download URL. Start an export with `POST /v1/audit-logs/export` first; this endpoint only reports and never starts one, so it is safe to poll.  **Statuses:** - `notStarted` — no archive exists for today's window and no build is running. Call `POST` to start one. - `running` — a build is in progress. Poll again in a few seconds. - `ready` — the archive is complete; `url` and `expiresAt` are present. - `failed` — the build did not finish; `error` carries a short reason. Call `POST` to try again.  **Format:** gzip-compressed NDJSON (`.ndjson.gz`) — one audit event per line, oldest first.  **Note:** the returned `url` expires within minutes — download promptly, and call this endpoint again for a fresh URL if it lapses. The archive itself persists for the rest of the UTC day. Actions taken by Voltage Park support/admin staff are attributed to their own organization and are not included here.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_audit_log_export_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AuditLogExportStatusResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_audit_log_export_serialize(
        self,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # Auto-generate idempotency key for mutation operations if not provided
        if self.api_client.configuration.auto_idempotency_key and 'GET' in ['POST', 'PUT', 'PATCH', 'DELETE']:
            if 'Idempotency-Key' not in _header_params:
                import uuid
                generator = self.api_client.configuration.idempotency_key_generator
                if generator:
                    _header_params['Idempotency-Key'] = generator()
                else:
                    _header_params['Idempotency-Key'] = str(uuid.uuid4())
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/audit-logs/export',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_audit_logs(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AuditLogListResponse:
        """List recent audit logs for your organization

        Returns the most recent audit events for the authenticated caller's organization — who did what, when, and from where. Scoped automatically to your organization (derived from your token); you cannot query another organization's activity.  **When to use:** - Let an organization owner review what users in their org have been doing - Investigate recent access or changes across your fleets  **Scope & limits (beta preview):** - Returns up to the 100 most recent events, newest first. - Covers recent activity only (a bounded lookback window). - No filtering or pagination yet — this is a preview feature and the contract may change.  **Note:** Actions taken by Voltage Park support/admin staff are attributed to their own organization and are not included here.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_audit_logs_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AuditLogListResponse",
            '401': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_audit_logs_with_http_info(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AuditLogListResponse]:
        """List recent audit logs for your organization

        Returns the most recent audit events for the authenticated caller's organization — who did what, when, and from where. Scoped automatically to your organization (derived from your token); you cannot query another organization's activity.  **When to use:** - Let an organization owner review what users in their org have been doing - Investigate recent access or changes across your fleets  **Scope & limits (beta preview):** - Returns up to the 100 most recent events, newest first. - Covers recent activity only (a bounded lookback window). - No filtering or pagination yet — this is a preview feature and the contract may change.  **Note:** Actions taken by Voltage Park support/admin staff are attributed to their own organization and are not included here.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_audit_logs_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AuditLogListResponse",
            '401': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_audit_logs_without_preload_content(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List recent audit logs for your organization

        Returns the most recent audit events for the authenticated caller's organization — who did what, when, and from where. Scoped automatically to your organization (derived from your token); you cannot query another organization's activity.  **When to use:** - Let an organization owner review what users in their org have been doing - Investigate recent access or changes across your fleets  **Scope & limits (beta preview):** - Returns up to the 100 most recent events, newest first. - Covers recent activity only (a bounded lookback window). - No filtering or pagination yet — this is a preview feature and the contract may change.  **Note:** Actions taken by Voltage Park support/admin staff are attributed to their own organization and are not included here.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_audit_logs_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AuditLogListResponse",
            '401': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_audit_logs_serialize(
        self,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # Auto-generate idempotency key for mutation operations if not provided
        if self.api_client.configuration.auto_idempotency_key and 'GET' in ['POST', 'PUT', 'PATCH', 'DELETE']:
            if 'Idempotency-Key' not in _header_params:
                import uuid
                generator = self.api_client.configuration.idempotency_key_generator
                if generator:
                    _header_params['Idempotency-Key'] = generator()
                else:
                    _header_params['Idempotency-Key'] = str(uuid.uuid4())
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/audit-logs',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def start_audit_log_export(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AuditLogExportStatusResponse:
        """Start building the 90-day audit log export for your organization

        Starts preparing a downloadable archive of your organization's audit events for the trailing 90 days, and returns immediately — building it takes longer than a request can wait. Poll `GET /v1/audit-logs/export` until `status` is `ready`, then download the `url` it returns. Scoped automatically to your organization (derived from your token); you cannot export another organization's activity.  **When to use:** - Produce 90 days of audit evidence for a SOC 2 or customer security review - Retain or analyze activity beyond the recent-events endpoint's bounded preview  **Window:** whole days only. The archive covers the 90 days ending at the most recent UTC midnight, so the current partial day is excluded and every caller on the same UTC day gets the identical archive. There are no parameters — the window is fixed, which is what makes the archive reusable.  **Idempotent:** safe to call repeatedly. If today's archive is already built this returns `ready` without doing any work; if a build is already running it returns `running` rather than starting a second one. At most one archive is built per organization per UTC day.  **Expect a wait** on the first call of a UTC day — typically under a minute, and longer for organizations with high activity. Subsequent calls the same day are immediate.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_audit_log_export_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "AuditLogExportStatusResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def start_audit_log_export_with_http_info(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AuditLogExportStatusResponse]:
        """Start building the 90-day audit log export for your organization

        Starts preparing a downloadable archive of your organization's audit events for the trailing 90 days, and returns immediately — building it takes longer than a request can wait. Poll `GET /v1/audit-logs/export` until `status` is `ready`, then download the `url` it returns. Scoped automatically to your organization (derived from your token); you cannot export another organization's activity.  **When to use:** - Produce 90 days of audit evidence for a SOC 2 or customer security review - Retain or analyze activity beyond the recent-events endpoint's bounded preview  **Window:** whole days only. The archive covers the 90 days ending at the most recent UTC midnight, so the current partial day is excluded and every caller on the same UTC day gets the identical archive. There are no parameters — the window is fixed, which is what makes the archive reusable.  **Idempotent:** safe to call repeatedly. If today's archive is already built this returns `ready` without doing any work; if a build is already running it returns `running` rather than starting a second one. At most one archive is built per organization per UTC day.  **Expect a wait** on the first call of a UTC day — typically under a minute, and longer for organizations with high activity. Subsequent calls the same day are immediate.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_audit_log_export_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "AuditLogExportStatusResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def start_audit_log_export_without_preload_content(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Start building the 90-day audit log export for your organization

        Starts preparing a downloadable archive of your organization's audit events for the trailing 90 days, and returns immediately — building it takes longer than a request can wait. Poll `GET /v1/audit-logs/export` until `status` is `ready`, then download the `url` it returns. Scoped automatically to your organization (derived from your token); you cannot export another organization's activity.  **When to use:** - Produce 90 days of audit evidence for a SOC 2 or customer security review - Retain or analyze activity beyond the recent-events endpoint's bounded preview  **Window:** whole days only. The archive covers the 90 days ending at the most recent UTC midnight, so the current partial day is excluded and every caller on the same UTC day gets the identical archive. There are no parameters — the window is fixed, which is what makes the archive reusable.  **Idempotent:** safe to call repeatedly. If today's archive is already built this returns `ready` without doing any work; if a build is already running it returns `running` rather than starting a second one. At most one archive is built per organization per UTC day.  **Expect a wait** on the first call of a UTC day — typically under a minute, and longer for organizations with high activity. Subsequent calls the same day are immediate.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_audit_log_export_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "AuditLogExportStatusResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '500': "ErrorResponse",
            '502': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _start_audit_log_export_serialize(
        self,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # Auto-generate idempotency key for mutation operations if not provided
        if self.api_client.configuration.auto_idempotency_key and 'POST' in ['POST', 'PUT', 'PATCH', 'DELETE']:
            if 'Idempotency-Key' not in _header_params:
                import uuid
                generator = self.api_client.configuration.idempotency_key_generator
                if generator:
                    _header_params['Idempotency-Key'] = generator()
                else:
                    _header_params['Idempotency-Key'] = str(uuid.uuid4())
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/audit-logs/export',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


